name: ci
on:
  on:
    schedule:
      - cron: "0 2 * * *" # every day at 2am
jobs:
  update-image:
    strategy:
      matrix:
        php_version: [ "7.2", "7.3", "7.4", "8.0", "8.1", "8.2" ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout the code
        uses: actions/checkout@v1
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: cli
          build-args: "PHP_VERSION=${{ matrix.php_version }}"
          platforms: linux/amd64,linux/arm64
          tags: patricksiemen/php-nginx-symfony:cli-${{ matrix.php_version }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: web
          build-args: "PHP_VERSION=${{ matrix.php_version }}"
          platforms: linux/amd64,linux/arm64
          tags: patricksiemen/php-nginx-symfony:web-${{ matrix.php_version }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: web-dev
          build-args: "PHP_VERSION=${{ matrix.php_version }}"
          platforms: linux/amd64,linux/arm64
          tags: patricksiemen/php-nginx-symfony:web-${{ matrix.php_version }}-dev
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # todo implement tests: https://github.com/siemendev/php-application-image/issues/2
